### ISSUE TITLE
Use aliases for students with middle names

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/mphowardlab.github.io#17]
We need to use aliases (e.g., without quotes) for anyone that goes by alternative versions of their names compared to how they are displayed.

@clpetix @pgkovakas 

You both can also decide how you want your name to show up. For example, Levi could do Levi Petix or C. Levi Petix instead of Chase 'Levi' Petix. I would use whatever your preferred / most common way is!

We can then use aliases if the way you publish is different (e.g., C. Levi Petix if Levi display as Levi Petix, or Penelope Grace Kovakas if Grace displays as Grace Kovakas)

**Comment by clpetix** [comment]
I would prefer C. Levi Petix be used. That way it will parallel my LinkedIn, Google Scholar, & professional twitter account.

**Comment by mphoward** [comment]
Fine by me! Feel free to update in the PR implementing any other changes.
