### ISSUE TITLE
Update software page

### ISSUE THREAD

**Issue by clpetix** [mphowardlab/mphowardlab.github.io#6]
relentless, flyft, lammpsio, Smolyak surrogate (with Dr. K), gsd-vmd plug-in

Include link to GitHub repository, link to documentation, short description, logo.

**Comment by clpetix** [comment]
@mphoward which software do you want included and what is the preferred ordering?

**Comment by mphoward** [comment]
Let’s start with:

relentless
flyft
azplugins
gsd-vmd
lammpsio
